### PR TITLE
fix 2 more warnings

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by yunnian** [comment]
Thank you agin!

**Comment by yunnian** [comment]
Are you using nsq queue ?

**Comment by remicollet** [comment]
> Are you using nsq queue ?

No, but I plan to add it to my RPM repository, among some other packages:
See https://blog.remirepo.net/pages/PECL-extensions-RPM-status

**Comment by remicollet** [comment]
Just uploaded to my repository, and announced
https://twitter.com/RemiRepository/status/976810589619187713

So Fedora users can simply `dnf install php-pecl-nsq`
And RHEL / CentOS users can simply `yum install php-pecl-nsq`

**Pull request merged**
